name: Android E2E

on:
  workflow_dispatch:

concurrency:
  group: android-e2e-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"

      - name: Setup Expo and EAS
        uses: expo/expo-github-action@v8
        with:
          expo-version: latest
          expo-cache: true
          eas-version: latest
          eas-cache: true
          packager: npm
          token: ${{ secrets.EXPO_TOKEN }}
          patch-watchers: true

      - name: Install npm packages
        run: npm ci

      - name: Build on EAS
        run: eas build --platform android --profile development --non-interactive

      - name: Setup Maestro
        run: curl -Ls https://get.maestro.mobile.dev | bash

      # https://github.com/ReactiveCircus/android-emulator-runner?tab=readme-ov-file#usage--examples
      - name: Enable KVM
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - name: run tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          # `sleep 1` を入れて`npm run android`がバックグラウンドで実行されるように
          script: |
            eas build:run --latest
            ~/.maestro/bin/maestro test maestro/home.yml
